export const highestOptions = {
  minutes: null,
  goals_scored: null,
  assists: null,
  clean_sheets: null,
  goals_conceded: null,
  own_goals: null,
  penalties_saved: null,
  penalties_missed: null,
  yellow_cards: null,
  red_cards: null,
  saves: null,
  bonus: null,
  bps: null,
  influence: null,
  creativity: null,
  threat: null,
  ict_index: null,
  total_points: null,
  in_dreamteam: null,
};
